### ISSUE TITLE
Wrong gyroscope info after shake

### ISSUE THREAD

**Issue by doteq** [KerJoe/MPU6050-Cemuhook-gyro#3]
First of all thank you so much for this project, when I found it, I've got a smile on my face that someone already did most work for me! However, I have an issue and I couldn't fix it by myself. When I'm gently rotating MPU6050 it works flawlessly, without drift or clipping.
![dX5QTg2Ie1](https://user-images.githubusercontent.com/24475901/150888735-0eefba1e-1882-4bb0-9468-ede1190b33ef.gif)
Although, when I shake it or just make some more intense movements, rotation shown by padtest is incorrect and the controller starts to drift
![vGqYRUKwfM](https://user-images.githubusercontent.com/24475901/150889205-f9e5a698-7fa4-46cb-a7e5-c48576f7ede5.gif)
(Note, that the position and rotation on the beggining and the end of gif are the same and it's in constant position on the end)
Do you have any ideas what I might have done wrong and how to fix it?

**Comment by KerJoe** [comment]
I see that you've closed the issue, but I'll comment anyway.

You can increase the gyro's range by changing `gyroSens` from 2 to 3.
You can also (probably) fix it by decreasing the `dataSendDelay`, too.

**Comment by doteq** [comment]
Yeah, changing sensitivity worked for me. Also, i found out, that joycons use ±8g acceleration range, so I changed that in the code. Hope it will help someone.
