### ISSUE TITLE
Optimize calibration experience

### ISSUE THREAD

**Issue by PlayXboxtion963** [KerJoe/MPU6050-Cemuhook-gyro#6]
Dear KerJoe:
    I have some suggestions after used your calibration code.

1. Some GIF user guide to let users know how to put them mpu6050 in calibration
2. combian calibration code with main code together.Auto save paraments in EEPROM after first calibration finish. if user want calibration again,Flash again.
3. IO Support. DSU Protocol support button info. So maybe some IO could be phyisic keys.
4. LED Info. Such like fast flash means connecting. Always light means connected.

**Comment by KerJoe** [comment]
Hello, about your suggestions:
1. I may add static pictures for all 3 steps of callibration. Though it would be much better if the written instructions could be improved enough not to require pictures.
2. I am not sure how necessary this is, a callibration sould be a one and done type of operation. However for now I will sepate the callibration sketch `setup()` body into separate functions, so they can be reused.
3. [The place](https://github.com/KerJoe/MPU6050-Cemuhook-gyro/blob/f4d50aada413e03ea76b8d47f282dd2c7f912cb2/gyro/gyro.ino#L215) where one needs to add input reading code is sufficiently commented, I think. If a user wishes to add input support they are free to add their own code for axis value measurement, button scanning, etc (the ESP8266 has a limited amount of I/O pins so I can't just assign random unused pins to buttons).
4. Ok, I'll add some blinking code when connecting, for the builtin LED.
